[package]
name = "advgpcgen-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

[[bin]]
name = "enum"
path = "src/enum.rs"

[[bin]]
name = "solve"
path = "src/solve.rs"
